title: My Dictionar
description: A personal dictionary and language reference
baseurl: ""
url: "https://merdeki.github.io/my-dictionary/"

collections:
  words:
    output: true
    permalink: /word/:name/

defaults:
  - scope:
      path: "_words"
      type: "words"
    values:
      layout: word
