title: Türkçe Sözlük
baseurl: "/my-dictionary"
url: "https://merdeki.github.io"
markdown: kramdown
theme: null

collections:
  entries:
    output: true
    permalink: /entries/:name/

defaults:
  - scope:
      path: "_entries"
      type: "entries"
    values:
      layout: "entry"
